# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastBMA_g <- function(x, nTimePoints, priorProbs_, oddsRatio, nVars, g, geneNames, start, end, nThreads, optimizeBits, maxOptimizeCycles, timeSeries, rankOnly, noPrune, edgeMin, edgeTol, pruneFilterMin, timeout) {
    .Call('networkBMA_fastBMA_g', PACKAGE = 'networkBMA', x, nTimePoints, priorProbs_, oddsRatio, nVars, g, geneNames, start, end, nThreads, optimizeBits, maxOptimizeCycles, timeSeries, rankOnly, noPrune, edgeMin, edgeTol, pruneFilterMin, timeout)
}

ScanBMA_BIC <- function(y, x, priorProbs_, oddsRatio) {
    .Call('networkBMA_ScanBMA_BIC', PACKAGE = 'networkBMA', y, x, priorProbs_, oddsRatio)
}

BMA_Diff_BIC <- function(y, x, priorProbs_, bestModel, diff100, diff0, pred100, pred0, minprob, epsilon) {
    .Call('networkBMA_BMA_Diff_BIC', PACKAGE = 'networkBMA', y, x, priorProbs_, bestModel, diff100, diff0, pred100, pred0, minprob, epsilon)
}

ScanBMA_g <- function(y, x, priorProbs_, oddsRatio, g) {
    .Call('networkBMA_ScanBMA_g', PACKAGE = 'networkBMA', y, x, priorProbs_, oddsRatio, g)
}

BMA_Diff_g <- function(y, x, priorProbs_, g, bestModel, diff100, diff0, pred100, pred0, minprob, epsilon) {
    .Call('networkBMA_BMA_Diff_g', PACKAGE = 'networkBMA', y, x, priorProbs_, g, bestModel, diff100, diff0, pred100, pred0, minprob, epsilon)
}

